[versions]
agp = "8.13.0"
androidGifDrawable = "1.2.29"
constraintlayout = "2.2.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
activityVersion = "1.8.0"

[libraries]
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
